window.GATEWAY = {
 "categories": [
  {
   "id": "start",
   "name": "Getting Started",
   "icon": "🚪",
   "desc": "Orientation tracks. “The Way to Hemi-Sync” explains the audio-guidance technology (hemispheric synchronization) that underlies everything here, and “What is Gateway Experience?” introduces the program as a whole."
  },
  {
   "id": "waves",
   "name": "The Gateway Waves",
   "icon": "🌊",
   "desc": "The core in-home training series, evolved from the Institute’s six-day Gateway Voyage. Eight Waves take you step by step through deeper Focus levels of consciousness, each building on the tools of the last. Use Hemi-Sync with stereo headphones, lying down, undisturbed."
  },
  {
   "id": "hplus",
   "name": "Human Plus (H+)",
   "icon": "⚡",
   "desc": "A self-enhancement system that guides you into a whole-brain state and opens the “Access Channel.” Each exercise encodes a short verbal “Function Command” — covering energy, immunity, sleep, focus and more — that you can later activate on demand in everyday life."
  },
  {
   "id": "explorer",
   "name": "Explorer Series",
   "icon": "🔭",
   "desc": "Actual lab recordings from the Institute’s Explorers Project: gifted subjects extending their consciousness into nonphysical realms and reporting back. Includes the celebrated sessions with the entity “Miranon” and Robert Monroe’s own commentary on the nature of reality."
  },
  {
   "id": "sessions",
   "name": "Explorers Sessions & Collection",
   "icon": "📼",
   "desc": "Raw, lightly edited archival session recordings (coded by explorer initials and date) from the original Explorer research — the source material behind the curated Explorer Series."
  },
  {
   "id": "radio",
   "name": "Gateway Radio Program",
   "icon": "🎙️",
   "desc": "Radio-style talks and interviews from the Institute, including conversations with Robert Monroe and consciousness researchers such as Charles T. Tart and Colin Wilson, exploring mind, matter and Hemi-Sync."
  },
  {
   "id": "cocreating",
   "name": "Co-Creating",
   "icon": "🤝",
   "desc": "A guided series on consciously shaping the future — visiting the year 2050 and working with the themes of Your World, Our World and Unity."
  },
  {
   "id": "music",
   "name": "Meditations & Music",
   "icon": "🎵",
   "desc": "Standalone Hemi-Sync meditations and verbal/musical pieces — chakra work, healing and serenity exercises, and atmospheric titles such as Hope, Joy and Golden Mean."
  },
  {
   "id": "joob",
   "name": "Journeys Out of the Body",
   "icon": "🌌",
   "desc": "The audio companion to Robert Monroe's landmark 1971 book. Hemi-Sync “Conditions” (A–D) guide you step by step toward inducing and stabilizing the out-of-body state, with an introduction by Bob Monroe himself."
  },
  {
   "id": "lucid",
   "name": "Lucid Dreaming",
   "icon": "🌙",
   "desc": "A Hemi-Sync exercise series for developing awareness within the dream state — recognizing, stabilizing and directing lucid dreams."
  },
  {
   "id": "mindfood",
   "name": "Mind Food",
   "icon": "🧠",
   "desc": "Hemi-Sync “Mind Food” exercises pairing deep relaxation with targeted mental states — concentration, memory, deep delta sleep and transcendence — in verbal and non-verbal forms."
  },
  {
   "id": "manifesting",
   "name": "Manifesting",
   "icon": "✨",
   "desc": "Joe Gallenberger's manifestation work: using the expanded, coherent states of Hemi-Sync to focus intention and consciously shape outcomes, with an interview and guided manifestation sessions."
  }
 ],
 "waves": {
  "1": {
   "name": "Discovery",
   "roman": "I",
   "focus": "Focus 10",
   "desc": "The foundation of the whole series. You are led from your normal waking state into deep relaxation and then into Focus 10 — the “mind awake, body asleep” state. These exercises establish the basic tools (Energy Conversion Box, Resonant Tuning, Resonant Energy Balloon) and let you discover new potentials in thought and action."
  },
  "2": {
   "name": "Threshold",
   "roman": "II",
   "focus": "Focus 12",
   "desc": "Threshold opens new perceptual channels and introduces Focus 12, a state of expanded awareness. The exercises develop creative insight and problem-solving while helping dissolve fear barriers, using tools such as Color Breathing, the Energy Bar Tool and Living Body Maps."
  },
  "3": {
   "name": "Freedom",
   "roman": "III",
   "focus": "Focus 12",
   "desc": "Freedom provides practice in separating your nonphysical self from your physical body. It includes Lift-Off, Remote Viewing, Vectors and First-Stage Separation — first steps toward controlled out-of-body exploration."
  },
  "4": {
   "name": "Adventure",
   "roman": "IV",
   "focus": "Focus 12",
   "desc": "The ultimate expression beyond Freedom: a personally controlled and directed adventure. Exercises like One-Year Patterning, Five Messages and Free Flow 12 let you set your own intent and explore with growing autonomy."
  },
  "5": {
   "name": "Exploring",
   "roman": "V",
   "focus": "Focus 15",
   "desc": "From the now-familiar Focus 12 you are introduced to Focus 15 — the “no-time” state, the state of simply being. Beyond the five physical senses you connect with the source of intuition, creation and manifestation. (Included here in both the Laurie Monroe 2004 and Honeycutt 2015 narrations, plus unpublished mission exercises.)"
  },
  "6": {
   "name": "Odyssey",
   "roman": "VI",
   "focus": "Focus 21",
   "desc": "A journey to Focus 21 — the bridge to other energy systems and realms beyond physical time-space reality. High-adventure exercises in sensing, expansion and free-flow journeys. (Includes the Laurie Monroe 2004 and Honeycutt 2015 narrations, plus the unpublished “Prospecting” exercises.)"
  },
  "7": {
   "name": "Voyager",
   "roman": "VII",
   "focus": "Focus 23–27",
   "desc": "Voyager moves through Focus 23, 25 and 27 — the states of awareness associated with the afterlife. You make contact with individuals who have died but remain tied to earth, and practice guiding (“retrieving”) them to a reception center to rest and review their lives."
  },
  "8": {
   "name": "Union",
   "roman": "VIII",
   "focus": "Focus 27",
   "desc": "Based on the Institute’s Exploration 27 program, Union is a tour of Focus 27 and “The Park”: meeting the Entry Director, the Educational, Healing & Regeneration, Planning and Coordination centers, Inner Earth, and ultimately The Absolute."
  }
 },
 "episodes": [
  {
   "n": 1,
   "title": "The Way to Hemi Sync",
   "file": "001 - The Way to Hemi Sync.mp3",
   "art": "_art/001.jpg",
   "dur": 1763900,
   "year": null,
   "cat": "start"
  },
  {
   "n": 2,
   "title": "Wave 1 - Discovery: Orientation (1996)",
   "file": "002 - Wave 1 - Discovery_ Orientation (1996).mp3",
   "art": "_art/002.jpg",
   "dur": 1987022,
   "year": "1996",
   "cat": "waves",
   "wave": 1,
   "subname": "Discovery",
   "unpublished": false,
   "flac": "Wave 1 (FLAC)/1 - Orientation.flac",
   "hifi": true
  },
  {
   "n": 3,
   "title": "Wave 1 - Discovery: Introduction to Focus10 (1996)",
   "file": "003 - Wave 1 - Discovery_ Introduction to Focus10 (1996).mp3",
   "art": "_art/003.jpg",
   "dur": 2229949,
   "year": "1996",
   "cat": "waves",
   "wave": 1,
   "subname": "Discovery",
   "unpublished": false,
   "flac": "Wave 1 (FLAC)/2 - Intro to Focus 10.flac",
   "hifi": true
  },
  {
   "n": 4,
   "title": "Wave 1 - Discovery: Advanced Focus10 (1996)",
   "file": "004 - Wave 1 - Discovery_ Advanced Focus10 (1996).mp3",
   "art": "_art/004.jpg",
   "dur": 2164712,
   "year": "1996",
   "cat": "waves",
   "wave": 1,
   "subname": "Discovery",
   "unpublished": false,
   "flac": "Wave 1 (FLAC)/3 - Advanced Focus 10.flac",
   "hifi": true
  },
  {
   "n": 5,
   "title": "Wave 1 - Discovery: Release and Recharging (1996)",
   "file": "005 - Wave 1 - Discovery_ Release and Recharging (1996).mp3",
   "art": "_art/005.jpg",
   "dur": 2160612,
   "year": "1996",
   "cat": "waves",
   "wave": 1,
   "subname": "Discovery",
   "unpublished": false,
   "flac": "Wave 1 (FLAC)/4 - Release and Recharge.flac",
   "hifi": true
  },
  {
   "n": 6,
   "title": "Wave 1 - Discovery: Exploration, Sleep (1996)",
   "file": "006 - Wave 1 - Discovery_ Exploration, Sleep (1996).mp3",
   "art": "_art/006.jpg",
   "dur": 2223181,
   "year": "1996",
   "cat": "waves",
   "wave": 1,
   "subname": "Discovery",
   "unpublished": false,
   "flac": "Wave 1 (FLAC)/5 - Exploration Sleep.flac",
   "hifi": true
  },
  {
   "n": 7,
   "title": "Wave 1 - Discovery: Free Flow Focus10 (1996)",
   "file": "007 - Wave 1 - Discovery_ Free Flow Focus10 (1996).mp3",
   "art": "_art/007.jpg",
   "dur": 2017954,
   "year": "1996",
   "cat": "waves",
   "wave": 1,
   "subname": "Discovery",
   "unpublished": false,
   "flac": "Wave 1 (FLAC)/6 - Free Flow 10.flac",
   "hifi": true
  },
  {
   "n": 8,
   "title": "Wave 2 - Threshold: Intro to Focus12 (1996)",
   "file": "008 - Wave 2 - Threshold_ Intro to Focus12 (1996).mp3",
   "art": "_art/008.jpg",
   "dur": 2103828,
   "year": "1996",
   "cat": "waves",
   "wave": 2,
   "subname": "Threshold",
   "unpublished": false,
   "flac": "Wave 2 (FLAC)/1 - Intro to Focus 12.flac",
   "hifi": true
  },
  {
   "n": 195,
   "title": "Wave 2 - Threshold: One Month Patterning (1996)",
   "file": "195 - Wave 2 - Threshold_ One Month Patterning.mp3",
   "art": "_art/195.jpg",
   "dur": 2303700,
   "year": "1996",
   "cat": "waves",
   "wave": 2,
   "subname": "Threshold",
   "unpublished": false
  },
  {
   "n": 9,
   "title": "Wave 2 - Threshold: Problem Solving (1996)",
   "file": "009 - Wave 2 - Threshold_ Problem Solving (1996).mp3",
   "art": "_art/009.jpg",
   "dur": 2217971,
   "year": "1996",
   "cat": "waves",
   "wave": 2,
   "subname": "Threshold",
   "unpublished": false,
   "flac": "Wave 2 (FLAC)/2 - Problem Solving.flac",
   "hifi": true
  },
  {
   "n": 10,
   "title": "Wave 2 - Threshold: Color Breathing (1996)",
   "file": "010 - Wave 2 - Threshold_ Color Breathing (1996).mp3",
   "art": "_art/010.jpg",
   "dur": 1798711,
   "year": "1996",
   "cat": "waves",
   "wave": 2,
   "subname": "Threshold",
   "unpublished": false,
   "flac": "Wave 2 (FLAC)/3 - Color Breathing.flac",
   "hifi": true
  },
  {
   "n": 11,
   "title": "Wave 2 - Threshold: Energy Bar Tool (1996)",
   "file": "011 - Wave 2 - Threshold_ Energy Bar Tool (1996).mp3",
   "art": "_art/011.jpg",
   "dur": 2100403,
   "year": "1996",
   "cat": "waves",
   "wave": 2,
   "subname": "Threshold",
   "unpublished": false,
   "flac": "Wave 2 (FLAC)/5 - Energy Bar Tool.flac",
   "hifi": true
  },
  {
   "n": 12,
   "title": "Wave 2 - Threshold: Living Body Maps (1996)",
   "file": "012 - Wave 2 - Threshold_ Living Body Maps (1996).mp3",
   "art": "_art/012.jpg",
   "dur": 2206649,
   "year": "1996",
   "cat": "waves",
   "wave": 2,
   "subname": "Threshold",
   "unpublished": false,
   "flac": "Wave 2 (FLAC)/6 - Living Body Map.flac",
   "hifi": true
  },
  {
   "n": 13,
   "title": "Wave 3 - Freedom: Lift Off (1996)",
   "file": "013 - Wave 3 - Freedom_ Lift Off (1996).mp3",
   "art": "_art/013.jpg",
   "dur": 1781938,
   "year": "1996",
   "cat": "waves",
   "wave": 3,
   "subname": "Freedom",
   "unpublished": false,
   "flac": "Wave 3 (FLAC)/1 - Lift Off.flac",
   "hifi": true
  },
  {
   "n": 14,
   "title": "Wave 3 - Freedom: Remote Viewing (1996)",
   "file": "014 - Wave 3 - Freedom_ Remote Viewing (1996).mp3",
   "art": "_art/014.jpg",
   "dur": 2115181,
   "year": "1996",
   "cat": "waves",
   "wave": 3,
   "subname": "Freedom",
   "unpublished": false,
   "flac": "Wave 3 (FLAC)/2 - Remote Viewing.flac",
   "hifi": true
  },
  {
   "n": 15,
   "title": "Wave 3 - Freedom: Vectors (1996)",
   "file": "015 - Wave 3 - Freedom_ Vectors (1996).mp3",
   "art": "_art/015.jpg",
   "dur": 1952156,
   "year": "1996",
   "cat": "waves",
   "wave": 3,
   "subname": "Freedom",
   "unpublished": false,
   "flac": "Wave 3 (FLAC)/3 - Vectors.flac",
   "hifi": true
  },
  {
   "n": 16,
   "title": "Wave 3 - Freedom: Five Questions (1996)",
   "file": "016 - Wave 3 - Freedom_ Five Questions (1996).mp3",
   "art": "_art/016.jpg",
   "dur": 2158160,
   "year": "1996",
   "cat": "waves",
   "wave": 3,
   "subname": "Freedom",
   "unpublished": false,
   "flac": "Wave 3 (FLAC)/4 - Five Questions.flac",
   "hifi": true
  },
  {
   "n": 17,
   "title": "Wave 3 - Freedom: Energy Foods (1996)",
   "file": "017 - Wave 3 - Freedom_ Energy Foods (1996).mp3",
   "art": "_art/017.jpg",
   "dur": 1968294,
   "year": "1996",
   "cat": "waves",
   "wave": 3,
   "subname": "Freedom",
   "unpublished": false,
   "flac": "Wave 3 (FLAC)/5 - Energy Food.flac",
   "hifi": true
  },
  {
   "n": 18,
   "title": "Wave 3 - Freedom: First Stage Separation (1996)",
   "file": "018 - Wave 3 - Freedom_ First Stage Separation (1996).mp3",
   "art": "_art/018.jpg",
   "dur": 2099606,
   "year": "1996",
   "cat": "waves",
   "wave": 3,
   "subname": "Freedom",
   "unpublished": false,
   "flac": "Wave 3 (FLAC)/6 - First Stage Separation.flac",
   "hifi": true
  },
  {
   "n": 19,
   "title": "Wave 4 - Adventure: One Year Patterning (1996)",
   "file": "019 - Wave 4 - Adventure_ One Year Patterning (1996).mp3",
   "art": "_art/019.jpg",
   "dur": 2062387,
   "year": "1996",
   "cat": "waves",
   "wave": 4,
   "subname": "Adventure",
   "unpublished": false,
   "flac": "Wave 4 (FLAC)/1 - One Year Patterning.flac",
   "hifi": true
  },
  {
   "n": 20,
   "title": "Wave 4 - Adventure: Five Messages (1996)",
   "file": "020 - Wave 4 - Adventure_ Five Messages (1996).mp3",
   "art": "_art/020.jpg",
   "dur": 2124000,
   "year": "1996",
   "cat": "waves",
   "wave": 4,
   "subname": "Adventure",
   "unpublished": false,
   "flac": "Wave 4 (FLAC)/2 - Five Messages.flac",
   "hifi": true
  },
  {
   "n": 21,
   "title": "Wave 4 - Adventure: Free Flow12 (1996)",
   "file": "021 - Wave 4 - Adventure_ Free Flow12 (1996).mp3",
   "art": "_art/021.jpg",
   "dur": 2107428,
   "year": "1996",
   "cat": "waves",
   "wave": 4,
   "subname": "Adventure",
   "unpublished": false,
   "flac": "Wave 4 (FLAC)/3 - Free Flow 12.flac",
   "hifi": true
  },
  {
   "n": 22,
   "title": "Wave 4 - Adventure: NVC (1996)",
   "file": "022 - Wave 4 - Adventure_ NVC (1996).mp3",
   "art": "_art/022.jpg",
   "dur": 2205586,
   "year": "1996",
   "cat": "waves",
   "wave": 4,
   "subname": "Adventure",
   "unpublished": false,
   "flac": "Wave 4 (FLAC)/4 - NVC 1.flac",
   "hifi": true
  },
  {
   "n": 23,
   "title": "Wave 4 - Adventure: NVC II (1996)",
   "file": "023 - Wave 4 - Adventure_ NVC II (1996).mp3",
   "art": "_art/023.jpg",
   "dur": 2734776,
   "year": "1996",
   "cat": "waves",
   "wave": 4,
   "subname": "Adventure",
   "unpublished": false,
   "flac": "Wave 4 (FLAC)/5 - NVC 2.flac",
   "hifi": true
  },
  {
   "n": 24,
   "title": "Wave 4 - Adventure: Compoint 12 (1996)",
   "file": "024 - Wave 4 - Adventure_ Compoint 12 (1996).mp3",
   "art": "_art/024.jpg",
   "dur": 1610788,
   "year": "1996",
   "cat": "waves",
   "wave": 4,
   "subname": "Adventure",
   "unpublished": false,
   "flac": "Wave 4 (FLAC)/6 - Compoint 12.flac",
   "hifi": true
  },
  {
   "n": 25,
   "title": "Wave 5 - Exploring: Advanced Focus 12 (Laurie M., 2004)",
   "file": "025 - Wave 5 - Exploring_ Advanced Focus 12 (Laurie M., 2004).mp3",
   "art": "_art/025.jpg",
   "dur": 2071569,
   "year": "2004",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false,
   "flac": "Wave 5 (FLAC)/1 - Advanced Focus 12.flac",
   "hifi": true
  },
  {
   "n": 26,
   "title": "Wave 5 - Exploring: Discovering Intuition (Laurie M., 2004)",
   "file": "026 - Wave 5 - Exploring_ Discovering Intuition (Laurie M., 2004).mp3",
   "art": "_art/026.jpg",
   "dur": 2072249,
   "year": "2004",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false,
   "flac": "Wave 5 (FLAC)/2 - Discovering Intuition.flac",
   "hifi": true
  },
  {
   "n": 27,
   "title": "Wave 5 - Exploring: Exploring Intuition (Laurie M., 2004)",
   "file": "027 - Wave 5 - Exploring_ Exploring Intuition (Laurie M., 2004).mp3",
   "art": "_art/027.jpg",
   "dur": 2070176,
   "year": "2004",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false,
   "flac": "Wave 5 (FLAC)/3 - Exploring Intuition.flac",
   "hifi": true
  },
  {
   "n": 28,
   "title": "Wave 5 - Exploring: Intro to Focus 15 (Laurie M, 2004)",
   "file": "028 - Wave 5 - Exploring_ Intro to Focus 15 (Laurie M, 2004).mp3",
   "art": "_art/028.jpg",
   "dur": 2099698,
   "year": "2004",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false,
   "flac": "Wave 5 (FLAC)/4 - Intro to Focus 15.flac",
   "hifi": true
  },
  {
   "n": 29,
   "title": "Wave 5 - Exploring: Mission 15, Creation and Manifestation (Laurie M, 2004)",
   "file": "029 - Wave 5 - Exploring_ Mission 15, Creation and Manifestation (Laurie M, 2004).mp3",
   "art": "_art/029.jpg",
   "dur": 2072175,
   "year": "2004",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false,
   "flac": "Wave 5 (FLAC)/5 - Mission 15 Creation and Manifestation.flac",
   "hifi": true
  },
  {
   "n": 30,
   "title": "Wave 5 - Exploring: Exploring Focus 15 (Laurie M, 2004)",
   "file": "030 - Wave 5 - Exploring_ Exploring Focus 15 (Laurie M, 2004).mp3",
   "art": "_art/030.jpg",
   "dur": 2296040,
   "year": "2004",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false,
   "flac": "Wave 5 (FLAC)/6 - Exploring Focus 15.flac",
   "hifi": true
  },
  {
   "n": 31,
   "title": "Wave 5 - Exploring: Advanced Focus 12 (Honeycutt, 2015)",
   "file": "031 - Wave 5 - Exploring_ Advanced Focus 12 (Honeycutt, 2015).mp3",
   "art": "_art/031.jpg",
   "dur": 2072900,
   "year": "2015",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false
  },
  {
   "n": 32,
   "title": "Wave 5 - Exploring: Discovering Intuition (Honeycutt, 2015)",
   "file": "032 - Wave 5 - Exploring_ Discovering Intuition (Honeycutt, 2015).mp3",
   "art": "_art/032.jpg",
   "dur": 2012200,
   "year": "2015",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false
  },
  {
   "n": 33,
   "title": "Wave 5 - Exploring: Exploring Intuition (Honeycutt, 2015)",
   "file": "033 - Wave 5 - Exploring_ Exploring Intuition (Honeycutt, 2015).mp3",
   "art": "_art/033.jpg",
   "dur": 2070600,
   "year": "2015",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false
  },
  {
   "n": 34,
   "title": "Wave 5 - Exploring: Introduction to Focus 15 (Honeycutt, 2015)",
   "file": "034 - Wave 5 - Exploring_ Introduction to Focus 15 (Honeycutt, 2015).mp3",
   "art": "_art/034.jpg",
   "dur": 2114900,
   "year": "2015",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false
  },
  {
   "n": 35,
   "title": "Wave 5 - Exploring: Mission 15 and Manifestation (Honeycutt, 2015)",
   "file": "035 - Wave 5 - Exploring_ Mission 15 and Manifestation (Honeycutt, 2015).mp3",
   "art": "_art/035.jpg",
   "dur": 2027600,
   "year": "2015",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false
  },
  {
   "n": 36,
   "title": "Wave 5 - Exploring: Exploring Focus 15 (Honeycutt, 2015)",
   "file": "036 - Wave 5 - Exploring_ Exploring Focus 15 (Honeycutt, 2015).mp3",
   "art": "_art/036.jpg",
   "dur": 2225100,
   "year": "2015",
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": false
  },
  {
   "n": 37,
   "title": "Wave 5 (Unpublished) - Exploring: Mission 10",
   "file": "037 - Wave 5 (Unpublished) - Exploring_ Mission 10.mp3",
   "art": "_art/037.jpg",
   "dur": 1793900,
   "year": null,
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": true
  },
  {
   "n": 38,
   "title": "Wave 5 (Unpublished) - Exploring: Mission Day",
   "file": "038 - Wave 5 (Unpublished) - Exploring_ Mission Day.mp3",
   "art": "_art/038.jpg",
   "dur": 972100,
   "year": null,
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": true
  },
  {
   "n": 39,
   "title": "Wave 5 (Unpublished) - Exploring: Mission Night",
   "file": "039 - Wave 5 (Unpublished) - Exploring_ Mission Night.mp3",
   "art": "_art/039.jpg",
   "dur": 1794300,
   "year": null,
   "cat": "waves",
   "wave": 5,
   "subname": "Exploring",
   "unpublished": true
  },
  {
   "n": 40,
   "title": "Wave 6 - Odyssey: Sensing in Locale 1 (Laurie M, 2004)",
   "file": "040 - Wave 6 - Odyssey_ Sensing in Locale 1 (Laurie M, 2004).mp3",
   "art": "_art/040.jpg",
   "dur": 2091356,
   "year": "2004",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false,
   "flac": "Wave 6 (FLAC)/1 - Sensing Locale 1.flac",
   "hifi": true
  },
  {
   "n": 41,
   "title": "Wave 6 - Odyssey: Expansion in Locale 1 (Laurie M, 2004)",
   "file": "041 - Wave 6 - Odyssey_ Expansion in Locale 1 (Laurie M, 2004).mp3",
   "art": "_art/041.jpg",
   "dur": 2056488,
   "year": "2004",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false,
   "flac": "Wave 6 (FLAC)/2 - Expansion in Locale 1.flac",
   "hifi": true
  },
  {
   "n": 42,
   "title": "Wave 6 - Odyssey: Point of Departure (Laurie M, 2004)",
   "file": "042 - Wave 6 - Odyssey_ Point of Departure (Laurie M, 2004).mp3",
   "art": "_art/042.jpg",
   "dur": 2082714,
   "year": "2004",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false,
   "flac": "Wave 6 (FLAC)/3 - Point of Departure.flac",
   "hifi": true
  },
  {
   "n": 43,
   "title": "Wave 6 - Odyssey: Nonphysical friends (Laurie M, 2004)",
   "file": "043 - Wave 6 - Odyssey_ Nonphysical friends (Laurie M, 2004).mp3",
   "art": "_art/043.jpg",
   "dur": 2161693,
   "year": "2004",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false,
   "flac": "Wave 6 (FLAC)/4 - Non Physical Friends.flac",
   "hifi": true
  },
  {
   "n": 44,
   "title": "Wave 6 - Odyssey: Mouvement to Locale 2, Intro Focus21 (Laurie M, 2004)",
   "file": "044 - Wave 6 - Odyssey_ Mouvement to Locale 2, Intro Focus21 (Laurie M, 2004).mp3",
   "art": "_art/044.jpg",
   "dur": 2017449,
   "year": "2004",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false,
   "flac": "Wave 6 (FLAC)/5 - Movement to Locale 2 - Intro to Focus 21.flac",
   "hifi": true
  },
  {
   "n": 45,
   "title": "Wave 6 - Odyssey: Free Flow Journey in Focus21 (Laurie M, 2004)",
   "file": "045 - Wave 6 - Odyssey_ Free Flow Journey in Focus21 (Laurie M, 2004).mp3",
   "art": "_art/045.jpg",
   "dur": 2405270,
   "year": "2004",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false,
   "flac": "Wave 6 (FLAC)/6 - Free Flow Journey in Focus 21.flac",
   "hifi": true
  },
  {
   "n": 46,
   "title": "Wave 6 - Odyssey: Sensing (Honeycutt, 2015)",
   "file": "046 - Wave 6 - Odyssey_ Sensing (Honeycutt, 2015).mp3",
   "art": "_art/046.jpg",
   "dur": 2069900,
   "year": "2015",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false
  },
  {
   "n": 47,
   "title": "Wave 6 - Odyssey: Expansion (Honeycutt, 2015)",
   "file": "047 - Wave 6 - Odyssey_ Expansion (Honeycutt, 2015).mp3",
   "art": "_art/047.jpg",
   "dur": 1911100,
   "year": "2015",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false
  },
  {
   "n": 48,
   "title": "Wave 6 - Odyssey: Point of Departure (Honeycutt, 2015)",
   "file": "048 - Wave 6 - Odyssey_ Point of Departure (Honeycutt, 2015).mp3",
   "art": "_art/048.jpg",
   "dur": 2005600,
   "year": "2015",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false
  },
  {
   "n": 49,
   "title": "Wave 6 - Odyssey: Non-Physical Friends (Honeycutt, 2015)",
   "file": "049 - Wave 6 - Odyssey_ Non-Physical Friends (Honeycutt, 2015).mp3",
   "art": "_art/049.jpg",
   "dur": 2118700,
   "year": "2015",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false
  },
  {
   "n": 50,
   "title": "Wave 6 - Odyssey: Intro to Focus 21 (Honeycutt, 2015)",
   "file": "050 - Wave 6 - Odyssey_ Intro to Focus 21 (Honeycutt, 2015).mp3",
   "art": "_art/050.jpg",
   "dur": 2017500,
   "year": "2015",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false
  },
  {
   "n": 51,
   "title": "Wave 6 - Odyssey: Freeflow Journey in Focus 21 (Honeycutt, 2015)",
   "file": "051 - Wave 6 - Odyssey_ Freeflow Journey in Focus 21 (Honeycutt, 2015).mp3",
   "art": "_art/051.jpg",
   "dur": 2372700,
   "year": "2015",
   "cat": "waves",
   "wave": 6,
   "subname": "Odyssey",
   "unpublished": false
  },
  {
   "n": 52,
   "title": "Wave 6 (Unpublished) - Prospecting: Metamorphosite",
   "file": "052 - Wave 6 (Unpublished) - Prospecting_ Metamorphosite.mp3",
   "art": "_art/052.jpg",
   "dur": 1746200,
   "year": null,
   "cat": "waves",
   "wave": 6,
   "subname": "Prospecting",
   "unpublished": true
  },
  {
   "n": 53,
   "title": "Wave 6 (Unpublished) - Prospecting: Bio-Body",
   "file": "053 - Wave 6 (Unpublished) - Prospecting_ Bio-Body.mp3",
   "art": "_art/053.jpg",
   "dur": 1792500,
   "year": null,
   "cat": "waves",
   "wave": 6,
   "subname": "Prospecting",
   "unpublished": true
  },
  {
   "n": 54,
   "title": "Wave 6 (Unpublished) - Prospecting: Null Point",
   "file": "054 - Wave 6 (Unpublished) - Prospecting_ Null Point.mp3",
   "art": "_art/054.jpg",
   "dur": 1857600,
   "year": null,
   "cat": "waves",
   "wave": 6,
   "subname": "Prospecting",
   "unpublished": true
  },
  {
   "n": 55,
   "title": "Wave 6 (Unpublished) - Prospecting: Plus Polarity",
   "file": "055 - Wave 6 (Unpublished) - Prospecting_ Plus Polarity.mp3",
   "art": "_art/055.jpg",
   "dur": 1787500,
   "year": null,
   "cat": "waves",
   "wave": 6,
   "subname": "Prospecting",
   "unpublished": true
  },
  {
   "n": 56,
   "title": "Wave 6 (Unpublished) - Prospecting: Near Reaches",
   "file": "056 - Wave 6 (Unpublished) - Prospecting_ Near Reaches.mp3",
   "art": "_art/056.jpg",
   "dur": 1851000,
   "year": null,
   "cat": "waves",
   "wave": 6,
   "subname": "Prospecting",
   "unpublished": true
  },
  {
   "n": 57,
   "title": "Wave 6 (Unpublished) - Prospecting: Far Reaches",
   "file": "057 - Wave 6 (Unpublished) - Prospecting_ Far Reaches.mp3",
   "art": "_art/057.jpg",
   "dur": 1785600,
   "year": null,
   "cat": "waves",
   "wave": 6,
   "subname": "Prospecting",
   "unpublished": true
  },
  {
   "n": 58,
   "title": "Wave 7 - Voyager: Explore Total Self (2019)",
   "file": "058 - Wave 7 - Voyager_ Explore Total Self (2019).mp3",
   "art": "_art/058.jpg",
   "dur": 2208923,
   "year": "2019",
   "cat": "waves",
   "wave": 7,
   "subname": "Voyager",
   "unpublished": false,
   "flac": "Wave 7 (FLAC)/1 - Explore Total Self.flac",
   "hifi": true
  },
  {
   "n": 59,
   "title": "Wave 7 - Voyager: Intro to Focus23 (2019)",
   "file": "059 - Wave 7 - Voyager_ Intro to Focus23 (2019).mp3",
   "art": "_art/059.jpg",
   "dur": 2465435,
   "year": "2019",
   "cat": "waves",
   "wave": 7,
   "subname": "Voyager",
   "unpublished": false,
   "flac": "Wave 7 (FLAC)/2 - Intro Focus 23.flac",
   "hifi": true
  },
  {
   "n": 60,
   "title": "Wave 7 - Voyager: Intro to Focus25 (2019)",
   "file": "060 - Wave 7 - Voyager_ Intro to Focus25 (2019).mp3",
   "art": "_art/060.jpg",
   "dur": 2200261,
   "year": "2019",
   "cat": "waves",
   "wave": 7,
   "subname": "Voyager",
   "unpublished": false,
   "flac": "Wave 7 (FLAC)/3 - Intro Focus 25.flac",
   "hifi": true
  },
  {
   "n": 61,
   "title": "Wave 7 - Voyager: Intro to Focus27 (2019)",
   "file": "061 - Wave 7 - Voyager_ Intro to Focus27 (2019).mp3",
   "art": "_art/061.jpg",
   "dur": 2500677,
   "year": "2019",
   "cat": "waves",
   "wave": 7,
   "subname": "Voyager",
   "unpublished": false,
   "flac": "Wave 7 (FLAC)/4 - Intro Focus 27.flac",
   "hifi": true
  },
  {
   "n": 62,
   "title": "Wave 7 - Voyager: Retrieval (2019)",
   "file": "062 - Wave 7 - Voyager_ Retrieval (2019).mp3",
   "art": "_art/062.jpg",
   "dur": 2532507,
   "year": "2019",
   "cat": "waves",
   "wave": 7,
   "subname": "Voyager",
   "unpublished": false,
   "flac": "Wave 7 (FLAC)/5 - First Retrieval.flac",
   "hifi": true
  },
  {
   "n": 63,
   "title": "Wave 7 - Voyager: Messages From Beyond (2019)",
   "file": "063 - Wave 7 - Voyager_ Messages From Beyond (2019).mp3",
   "art": "_art/063.jpg",
   "dur": 1765963,
   "year": "2019",
   "cat": "waves",
   "wave": 7,
   "subname": "Voyager",
   "unpublished": false,
   "flac": "Wave 7 (FLAC)/6 - Messages From Beyond.flac",
   "hifi": true
  },
  {
   "n": 64,
   "title": "Wave 8 - Union: Special Tour (2022)",
   "file": "064 - Wave 8 - Union_ Special Tour (2022).mp3",
   "art": "_art/064.jpg",
   "dur": 2279955,
   "year": "2022",
   "cat": "waves",
   "wave": 8,
   "subname": "Union",
   "unpublished": false,
   "flac": "Wave 8 (FLAC)/1 - Special Tour.flac",
   "hifi": true
  },
  {
   "n": 65,
   "title": "Wave 8 - Union: Meeting with the Entry Director (2022)",
   "file": "065 - Wave 8 - Union_ Meeting with the Entry Director (2022).mp3",
   "art": "_art/065.jpg",
   "dur": 2279988,
   "year": "2022",
   "cat": "waves",
   "wave": 8,
   "subname": "Union",
   "unpublished": false,
   "flac": "Wave 8 (FLAC)/2 - Meeting with the Entry Director.flac",
   "hifi": true
  },
  {
   "n": 66,
   "title": "Wave 8 - Union: Educational Opportunities (2022)",
   "file": "066 - Wave 8 - Union_ Educational Opportunities (2022).mp3",
   "art": "_art/066.jpg",
   "dur": 2279993,
   "year": "2022",
   "cat": "waves",
   "wave": 8,
   "subname": "Union",
   "unpublished": false,
   "flac": "Wave 8 (FLAC)/3 - Educational Opportunities.flac",
   "hifi": true
  },
  {
   "n": 67,
   "title": "Wave 8 - Union: Healing and Regeneration Center (2022)",
   "file": "067 - Wave 8 - Union_ Healing and Regeneration Center (2022).mp3",
   "art": "_art/067.jpg",
   "dur": 2279990,
   "year": "2022",
   "cat": "waves",
   "wave": 8,
   "subname": "Union",
   "unpublished": false,
   "flac": "Wave 8 (FLAC)/4 - Healing and Regeneration Center.flac",
   "hifi": true
  },
  {
   "n": 68,
   "title": "Wave 8 - Union: The Planning Center (2022)",
   "file": "068 - Wave 8 - Union_ The Planning Center (2022).mp3",
   "art": "_art/068.jpg",
   "dur": 2279993,
   "year": "2022",
   "cat": "waves",
   "wave": 8,
   "subname": "Union",
   "unpublished": false,
   "flac": "Wave 8 (FLAC)/5 - Planning Center.flac",
   "hifi": true
  },
  {
   "n": 69,
   "title": "Wave 8 - Union: Coordination Area (2022)",
   "file": "069 - Wave 8 - Union_ Coordination Area (2022).mp3",
   "art": "_art/069.jpg",
   "dur": 2279993,
   "year": "2022",
   "cat": "waves",
   "wave": 8,
   "subname": "Union",
   "unpublished": false,
   "flac": "Wave 8 (FLAC)/6 - Coordination Area.flac",
   "hifi": true
  },
  {
   "n": 70,
   "title": "Wave 8 - Union: Inner Earth (2022)",
   "file": "070 - Wave 8 - Union_ Inner Earth (2022).mp3",
   "art": "_art/070.jpg",
   "dur": 2279993,
   "year": "2022",
   "cat": "waves",
   "wave": 8,
   "subname": "Union",
   "unpublished": false,
   "flac": "Wave 8 (FLAC)/7 - Inner Earth.flac",
   "hifi": true
  },
  {
   "n": 71,
   "title": "Wave 8 - Union: The Absolute (2022)",
   "file": "071 - Wave 8 - Union_ The Absolute (2022).mp3",
   "art": "_art/071.jpg",
   "dur": 2279993,
   "year": "2022",
   "cat": "waves",
   "wave": 8,
   "subname": "Union",
   "unpublished": false,
   "flac": "Wave 8 (FLAC)/8 - The Absolute.flac",
   "hifi": true
  },
  {
   "n": 72,
   "title": "What is Gateway Experience?",
   "file": "072 - What is Gateway Experience_.mp3",
   "art": "_art/072.jpg",
   "dur": 2258000,
   "year": null,
   "cat": "start"
  },
  {
   "n": 73,
   "title": "Human Plus: Let-Go #1",
   "file": "073 - Human Plus_ Let-Go #1.mp3",
   "art": "_art/073.jpg",
   "dur": 1663000,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 74,
   "title": "Human Plus: Let-Go #2",
   "file": "074 - Human Plus_ Let-Go #2.mp3",
   "art": "_art/074.jpg",
   "dur": 1710000,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 75,
   "title": "Human Plus: Möbius West #1",
   "file": "075 - Human Plus_ Möbius West #1.mp3",
   "art": "_art/075.jpg",
   "dur": 1744100,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 76,
   "title": "Human Plus: Möbius West #2",
   "file": "076 - Human Plus_ Möbius West #2.mp3",
   "art": "_art/076.jpg",
   "dur": 1765700,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 77,
   "title": "Human Plus: Passages #1",
   "file": "077 - Human Plus_ Passages #1.mp3",
   "art": "_art/077.jpg",
   "dur": 1679300,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 78,
   "title": "Human Plus: Passages #2",
   "file": "078 - Human Plus_ Passages #2.mp3",
   "art": "_art/078.jpg",
   "dur": 2078700,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 79,
   "title": "Human Plus: Relax #1",
   "file": "079 - Human Plus_ Relax #1.mp3",
   "art": "_art/079.jpg",
   "dur": 1630400,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 80,
   "title": "Human Plus: Relax #2",
   "file": "080 - Human Plus_ Relax #2.mp3",
   "art": "_art/080.jpg",
   "dur": 1737500,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 81,
   "title": "Human Plus: Circulation #1",
   "file": "081 - Human Plus_ Circulation #1.mp3",
   "art": "_art/081.jpg",
   "dur": 1649200,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 82,
   "title": "Human Plus: Circulation #2",
   "file": "082 - Human Plus_ Circulation #2.mp3",
   "art": "_art/082.jpg",
   "dur": 1760500,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 83,
   "title": "Human Plus: Contemplation",
   "file": "083 - Human Plus_ Contemplation.mp3",
   "art": "_art/083.jpg",
   "dur": 1717200,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 84,
   "title": "Human Plus: De-Tox Body",
   "file": "084 - Human Plus_ De-Tox Body.mp3",
   "art": "_art/084.jpg",
   "dur": 1706000,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 85,
   "title": "Human Plus: De-Hab #1",
   "file": "085 - Human Plus_ De-Hab #1.mp3",
   "art": "_art/085.jpg",
   "dur": 1723900,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 86,
   "title": "Human Plus: De-Hab #2",
   "file": "086 - Human Plus_ De-Hab #2.mp3",
   "art": "_art/086.jpg",
   "dur": 1688600,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 87,
   "title": "Human Plus: Do This Now #1",
   "file": "087 - Human Plus_ Do This Now #1.mp3",
   "art": "_art/087.jpg",
   "dur": 1711100,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 88,
   "title": "Human Plus: Do This Now #2",
   "file": "088 - Human Plus_ Do This Now #2.mp3",
   "art": "_art/088.jpg",
   "dur": 1764100,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 89,
   "title": "Human Plus: Eat-No Eat",
   "file": "089 - Human Plus_ Eat-No Eat.mp3",
   "art": "_art/089.jpg",
   "dur": 1066200,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 90,
   "title": "Human Plus: Eight-Great #1",
   "file": "090 - Human Plus_ Eight-Great #1.mp3",
   "art": "_art/090.jpg",
   "dur": 1660900,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 91,
   "title": "Human Plus: Eight-Great #2",
   "file": "091 - Human Plus_ Eight-Great #2.mp3",
   "art": "_art/091.jpg",
   "dur": 1721900,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 92,
   "title": "Human Plus: Immunizing",
   "file": "092 - Human Plus_ Immunizing.mp3",
   "art": "_art/092.jpg",
   "dur": 398700,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 93,
   "title": "Human Plus: Lungs, Support & Maintenance",
   "file": "093 - Human Plus_ Lungs, Support & Maintenance.mp3",
   "art": "_art/093.jpg",
   "dur": 1788600,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 94,
   "title": "Human Plus: Off-Loading",
   "file": "094 - Human Plus_ Off-Loading.mp3",
   "art": "_art/094.jpg",
   "dur": 90500,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 95,
   "title": "Human Plus: Recall",
   "file": "095 - Human Plus_ Recall.mp3",
   "art": "_art/095.jpg",
   "dur": 411500,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 96,
   "title": "Human Plus: Heart, Support & Maintenance #1",
   "file": "096 - Human Plus_ Heart, Support & Maintenance #1.mp3",
   "art": "_art/096.jpg",
   "dur": 1662200,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 97,
   "title": "Human Plus: Heart, Support & Maintenance #2",
   "file": "097 - Human Plus_ Heart, Support & Maintenance #2.mp3",
   "art": "_art/097.jpg",
   "dur": 1691000,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 98,
   "title": "Human Plus: Hypertension",
   "file": "098 - Human Plus_ Hypertension.mp3",
   "art": "_art/098.jpg",
   "dur": 1790900,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 99,
   "title": "Meditation Hemi Sync",
   "file": "099 - Meditation Hemi Sync.mp3",
   "art": "_art/099.jpg",
   "dur": 2698100,
   "year": null,
   "cat": "music"
  },
  {
   "n": 100,
   "title": "Chronotope Project: Quest of the Mystic",
   "file": "100 - Chronotope Project_ Quest of the Mystic.mp3",
   "art": "_art/100.jpg",
   "dur": 3286900,
   "year": null,
   "cat": "music"
  },
  {
   "n": 101,
   "title": "Human Plus: Synchronizing",
   "file": "101 - Human Plus_ Synchronizing.mp3",
   "art": "_art/101.jpg",
   "dur": 732100,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 102,
   "title": "Human Plus: Sex Drive",
   "file": "102 - Human Plus_ Sex Drive.mp3",
   "art": "_art/102.jpg",
   "dur": 929700,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 103,
   "title": "Human Plus: Tune-Up",
   "file": "103 - Human Plus_ Tune-Up.mp3",
   "art": "_art/103.jpg",
   "dur": 1632600,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 104,
   "title": "Human Plus: Think Fast",
   "file": "104 - Human Plus_ Think Fast.mp3",
   "art": "_art/104.jpg",
   "dur": 1576800,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 105,
   "title": "Chakra Meditation #1",
   "file": "105 - Chakra Meditation #1.mp3",
   "art": "_art/105.jpg",
   "dur": 3018400,
   "year": null,
   "cat": "music"
  },
  {
   "n": 106,
   "title": "Chakra Meditation #2",
   "file": "106 - Chakra Meditation #2.mp3",
   "art": "_art/106.jpg",
   "dur": 1354200,
   "year": null,
   "cat": "music"
  },
  {
   "n": 107,
   "title": "Guide To Serenity",
   "file": "107 - Guide To Serenity.mp3",
   "art": "_art/107.jpg",
   "dur": 2349100,
   "year": null,
   "cat": "music"
  },
  {
   "n": 108,
   "title": "Human Plus: Restorative Sleep",
   "file": "108 - Human Plus_ Restorative Sleep.mp3",
   "art": "_art/108.jpg",
   "dur": 378800,
   "year": null,
   "cat": "hplus"
  },
  {
   "n": 109,
   "title": "Mind Food: Message From Bob",
   "file": "109 - Mind Food_ Message From Bob.mp3",
   "art": "_art/109.jpg",
   "dur": 1462000,
   "year": null,
   "cat": "music"
  },
  {
   "n": 110,
   "title": "Co-creating: Visiting the Year 2050",
   "file": "110 - Co-creating_ Visiting the Year 2050.mp3",
   "art": "_art/110.jpg",
   "dur": 1995000,
   "year": null,
   "cat": "cocreating"
  },
  {
   "n": 111,
   "title": "Co-Creating: Your World",
   "file": "111 - Co-Creating_ Your World.mp3",
   "art": "_art/111.jpg",
   "dur": 2125400,
   "year": null,
   "cat": "cocreating"
  },
  {
   "n": 112,
   "title": "Co-Creating: Our World",
   "file": "112 - Co-Creating_ Our World.mp3",
   "art": "_art/112.jpg",
   "dur": 1991900,
   "year": null,
   "cat": "cocreating"
  },
  {
   "n": 113,
   "title": "Co-Creating: Unity",
   "file": "113 - Co-Creating_ Unity.mp3",
   "art": "_art/113.jpg",
   "dur": 2240900,
   "year": null,
   "cat": "cocreating"
  },
  {
   "n": 114,
   "title": "Thursday",
   "file": "114 - Thursday.mp3",
   "art": "_art/114.jpg",
   "dur": 1508800,
   "year": null,
   "cat": "music"
  },
  {
   "n": 115,
   "title": "Hemi-Sync: Dolphin Healing",
   "file": "115 - Hemi-Sync_ Dolphin Healing.mp3",
   "art": "_art/115.jpg",
   "dur": 562000,
   "year": null,
   "cat": "music"
  },
  {
   "n": 116,
   "title": "Connecting with the Inner Creator",
   "file": "116 - Connecting with the Inner Creator.mp3",
   "art": "_art/116.jpg",
   "dur": 1835600,
   "year": null,
   "cat": "music"
  },
  {
   "n": 117,
   "title": "Gateway Radio Program: Hemi-Sync and Awareness",
   "file": "117 - Gateway Radio Program_ Hemi-Sync and Awareness.mp3",
   "art": "_art/117.jpg",
   "dur": 3167700,
   "year": null,
   "cat": "radio"
  },
  {
   "n": 118,
   "title": "Hope",
   "file": "118 - Hope.mp3",
   "art": "_art/118.jpg",
   "dur": 1807800,
   "year": null,
   "cat": "music"
  },
  {
   "n": 119,
   "title": "Gateway Radio Program: Psychic Spying",
   "file": "119 - Gateway Radio Program_ Psychic Spying.mp3",
   "art": "_art/119.jpg",
   "dur": 3466200,
   "year": null,
   "cat": "radio"
  },
  {
   "n": 120,
   "title": "Impression of Solitude",
   "file": "120 - Impression of Solitude.mp3",
   "art": "_art/120.jpg",
   "dur": 1636900,
   "year": null,
   "cat": "music"
  },
  {
   "n": 121,
   "title": "Gateway Radio Program: Interview with Robert Monroe",
   "file": "121 - Gateway Radio Program_ Interview with Robert Monroe.mp3",
   "art": "_art/121.jpg",
   "dur": 3243500,
   "year": null,
   "cat": "radio"
  },
  {
   "n": 122,
   "title": "Access to Energy",
   "file": "122 - Access to Energy.mp3",
   "art": "_art/122.jpg",
   "dur": 2360900,
   "year": null,
   "cat": "music"
  },
  {
   "n": 123,
   "title": "Explorer Series: Communications with Nonphysical Entities",
   "file": "123 - Explorer Series_ Communications with Nonphysical Entities.mp3",
   "art": "_art/123.jpg",
   "dur": 2338000,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 124,
   "title": "Explorer Series: An Explorer’s Past-Life Regressions",
   "file": "124 - Explorer Series_ An Explorer’s Past-Life Regressions.mp3",
   "art": "_art/124.jpg",
   "dur": 2362700,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 125,
   "title": "Explorer Series: Consciousness and New Technology",
   "file": "125 - Explorer Series_ Consciousness and New Technology.mp3",
   "art": "_art/125.jpg",
   "dur": 2382500,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 126,
   "title": "Prophet's Message",
   "file": "126 - Prophet's Message.mp3",
   "art": "_art/126.jpg",
   "dur": 1738700,
   "year": null,
   "cat": "music"
  },
  {
   "n": 127,
   "title": "Gateway Radio Program: Mind and Matter",
   "file": "127 - Gateway Radio Program_ Mind and Matter.mp3",
   "art": "_art/127.jpg",
   "dur": 3663300,
   "year": null,
   "cat": "radio"
  },
  {
   "n": 128,
   "title": "Explorer Series: Multidimensional Aspects of the Self",
   "file": "128 - Explorer Series_ Multidimensional Aspects of the Self.mp3",
   "art": "_art/128.jpg",
   "dur": 2116500,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 129,
   "title": "Explorer Series: Introduction to Miranon",
   "file": "129 - Explorer Series_ Introduction to Miranon.mp3",
   "art": "_art/129.jpg",
   "dur": 3359500,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 130,
   "title": "Explorer Series: Miranon - Levels and Planes of Existence",
   "file": "130 - Explorer Series_ Miranon - Levels and Planes of Existence.mp3",
   "art": "_art/130.jpg",
   "dur": 3349700,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 131,
   "title": "Explorer Series: Awareness of True Reality",
   "file": "131 - Explorer Series_ Awareness of True Reality.mp3",
   "art": "_art/131.jpg",
   "dur": 3420300,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 132,
   "title": "Explorer Series: Breaking Thought Barriers",
   "file": "132 - Explorer Series_ Breaking Thought Barriers.mp3",
   "art": "_art/132.jpg",
   "dur": 3477300,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 133,
   "title": "Joy",
   "file": "133 - Joy.mp3",
   "art": "_art/133.jpg",
   "dur": 2654600,
   "year": null,
   "cat": "music"
  },
  {
   "n": 134,
   "title": "Gateway Radio Program: Charles T. Tart, Ph.D.",
   "file": "134 - Gateway Radio Program_ Charles T. Tart, Ph.D..mp3",
   "art": "_art/134.jpg",
   "dur": 3245400,
   "year": null,
   "cat": "radio"
  },
  {
   "n": 135,
   "title": "Explorer Series: Earth Changes",
   "file": "135 - Explorer Series_ Earth Changes.mp3",
   "art": "_art/135.jpg",
   "dur": 3466200,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 136,
   "title": "Explorer Series: Physical Existence - Perceptions from the Other Side",
   "file": "136 - Explorer Series_ Physical Existence - Perceptions from the Other Side.mp3",
   "art": "_art/136.jpg",
   "dur": 3396800,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 137,
   "title": "Explorer Series: Responsibility of Self",
   "file": "137 - Explorer Series_ Responsibility of Self.mp3",
   "art": "_art/137.jpg",
   "dur": 3334700,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 138,
   "title": "Explorer Series: Levels of Human Consciousness",
   "file": "138 - Explorer Series_ Levels of Human Consciousness.mp3",
   "art": "_art/138.jpg",
   "dur": 3286900,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 139,
   "title": "Explorer Series: Miranon - Human Existence",
   "file": "139 - Explorer Series_ Miranon - Human Existence.mp3",
   "art": "_art/139.jpg",
   "dur": 3087000,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 140,
   "title": "Golden Mean",
   "file": "140 - Golden Mean.mp3",
   "art": "_art/140.jpg",
   "dur": 2461700,
   "year": null,
   "cat": "music"
  },
  {
   "n": 141,
   "title": "Gateway Radio Program: Justine Owens, Ph.D. and Gari Carter",
   "file": "141 - Gateway Radio Program_ Justine Owens, Ph.D. and Gari Carter.mp3",
   "art": "_art/141.jpg",
   "dur": 3563400,
   "year": null,
   "cat": "radio"
  },
  {
   "n": 142,
   "title": "Explorer Series: Miranon - The Brain and Higher Consciousness",
   "file": "142 - Explorer Series_ Miranon - The Brain and Higher Consciousness.mp3",
   "art": "_art/142.jpg",
   "dur": 3254600,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 143,
   "title": "Explorer Series: Energy and the Physical Body",
   "file": "143 - Explorer Series_ Energy and the Physical Body.mp3",
   "art": "_art/143.jpg",
   "dur": 2919800,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 144,
   "title": "Explorer Series: Male-Female Principles Within the Self",
   "file": "144 - Explorer Series_ Male-Female Principles Within the Self.mp3",
   "art": "_art/144.jpg",
   "dur": 3289900,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 145,
   "title": "Explorer Series: Patrick - A Rescue Mission",
   "file": "145 - Explorer Series_ Patrick - A Rescue Mission.mp3",
   "art": "_art/145.jpg",
   "dur": 3427600,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 146,
   "title": "Explorer Series: Story of the Creation",
   "file": "146 - Explorer Series_ Story of the Creation.mp3",
   "art": "_art/146.jpg",
   "dur": 3149100,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 147,
   "title": "Rejuvenation",
   "file": "147 - Rejuvenation.mp3",
   "art": "_art/147.jpg",
   "dur": 2252800,
   "year": null,
   "cat": "music"
  },
  {
   "n": 148,
   "title": "Gateway Radio Program: Colin Wilson",
   "file": "148 - Gateway Radio Program_ Colin Wilson.mp3",
   "art": "_art/148.jpg",
   "dur": 3492400,
   "year": null,
   "cat": "radio"
  },
  {
   "n": 149,
   "title": "Explorer Series: Love, Fear, and Higher Consciousness",
   "file": "149 - Explorer Series_ Love, Fear, and Higher Consciousness.mp3",
   "art": "_art/149.jpg",
   "dur": 3276900,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 150,
   "title": "Explorer Series: Attachments as Stumbling Blocks",
   "file": "150 - Explorer Series_ Attachments as Stumbling Blocks.mp3",
   "art": "_art/150.jpg",
   "dur": 5020600,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 151,
   "title": "Explorer Series: A Meeting with Father Time",
   "file": "151 - Explorer Series_ A Meeting with Father Time.mp3",
   "art": "_art/151.jpg",
   "dur": 3213700,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 152,
   "title": "Explorer Series: Lessons that Man Must Learn",
   "file": "152 - Explorer Series_ Lessons that Man Must Learn.mp3",
   "art": "_art/152.jpg",
   "dur": 3142800,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 153,
   "title": "Explorer Series: Robert Monroe - Life as Wave Forms",
   "file": "153 - Explorer Series_ Robert Monroe - Life as Wave Forms.mp3",
   "art": "_art/153.jpg",
   "dur": 3416400,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 154,
   "title": "One With All",
   "file": "154 - One With All.mp3",
   "art": "_art/154.jpg",
   "dur": 2463500,
   "year": null,
   "cat": "music"
  },
  {
   "n": 155,
   "title": "Gateway Radio Program: Rosalind A. McKnight",
   "file": "155 - Gateway Radio Program_ Rosalind A. McKnight.mp3",
   "art": "_art/155.jpg",
   "dur": 3835400,
   "year": null,
   "cat": "radio"
  },
  {
   "n": 156,
   "title": "Explorer Series: Robert Monroe - Laboratory Procedures",
   "file": "156 - Explorer Series_ Robert Monroe - Laboratory Procedures.mp3",
   "art": "_art/156.jpg",
   "dur": 2877900,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 157,
   "title": "Explorer Series: The Importance of Thought Forms",
   "file": "157 - Explorer Series_ The Importance of Thought Forms.mp3",
   "art": "_art/157.jpg",
   "dur": 2452600,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 158,
   "title": "Explorer Series: Becoming an Explorer",
   "file": "158 - Explorer Series_ Becoming an Explorer.mp3",
   "art": "_art/158.jpg",
   "dur": 2080500,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 159,
   "title": "Explorer Series: The Origins of Man",
   "file": "159 - Explorer Series_ The Origins of Man.mp3",
   "art": "_art/159.jpg",
   "dur": 4776600,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 160,
   "title": "Explorer Series: Collective Consciousness",
   "file": "160 - Explorer Series_ Collective Consciousness.mp3",
   "art": "_art/160.jpg",
   "dur": 467000,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 161,
   "title": "Healing Energies",
   "file": "161 - Healing Energies.mp3",
   "art": "_art/161.jpg",
   "dur": 2633600,
   "year": null,
   "cat": "music"
  },
  {
   "n": 162,
   "title": "Access to Information",
   "file": "162 - Access to Information.mp3",
   "art": "_art/162.jpg",
   "dur": 2562700,
   "year": null,
   "cat": "music"
  },
  {
   "n": 163,
   "title": "Explorer Series: Aspects",
   "file": "163 - Explorer Series_ Aspects.mp3",
   "art": "_art/163.jpg",
   "dur": 1599200,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 164,
   "title": "Explorer Series: Personal Development",
   "file": "164 - Explorer Series_ Personal Development.mp3",
   "art": "_art/164.jpg",
   "dur": 4039300,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 165,
   "title": "Explorer Series: Entities, Energy Streams and Information Services",
   "file": "165 - Explorer Series_ Entities, Energy Streams and Information Services.mp3",
   "art": "_art/165.jpg",
   "dur": 2483000,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 166,
   "title": "Explorer Series: Seeking Personal Guidance",
   "file": "166 - Explorer Series_ Seeking Personal Guidance.mp3",
   "art": "_art/166.jpg",
   "dur": 1872800,
   "year": null,
   "cat": "explorer"
  },
  {
   "n": 167,
   "title": "Explorers Session with JR - 01a",
   "file": "167 - Explorers Session with JR - 01a.mp3",
   "art": "_art/167.jpg",
   "dur": 1126900,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 168,
   "title": "Explorers Session with LRB - 02a",
   "file": "168 - Explorers Session with LRB - 02a.mp3",
   "art": "_art/168.jpg",
   "dur": 1751400,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 169,
   "title": "Messages From Beyond",
   "file": "169 - Messages From Beyond.mp3",
   "art": "_art/169.jpg",
   "dur": 2026900,
   "year": null,
   "cat": "music"
  },
  {
   "n": 170,
   "title": "Explorers Session with LRB - 01",
   "file": "170 - Explorers Session with LRB - 01.mp3",
   "art": "_art/170.jpg",
   "dur": 2586500,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 171,
   "title": "Explorers Session with LGR - 2",
   "file": "171 - Explorers Session with LGR - 2.mp3",
   "art": "_art/171.jpg",
   "dur": 1546700,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 172,
   "title": "Explorers Session with FRB - 01",
   "file": "172 - Explorers Session with FRB - 01.mp3",
   "art": "_art/172.jpg",
   "dur": 2449200,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 173,
   "title": "Explorers Collection #6 - TNW-2 04-05-1984]",
   "file": "173 - Explorers Collection #6 - TNW-2 04-05-1984].mp3",
   "art": "_art/173.jpg",
   "dur": 1715100,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 174,
   "title": "Explorers Collection #7 - HRW-1 [08-04-1984]",
   "file": "174 - Explorers Collection #7 - HRW-1 [08-04-1984].mp3",
   "art": "_art/174.jpg",
   "dur": 2428200,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 175,
   "title": "Explorers Collection #8 - LLJ-2 [04-06-1986]",
   "file": "175 - Explorers Collection #8 - LLJ-2 [04-06-1986].mp3",
   "art": "_art/175.jpg",
   "dur": 2330900,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 176,
   "title": "Meeting with Muses",
   "file": "176 - Meeting with Muses.mp3",
   "art": "_art/176.jpg",
   "dur": 2435800,
   "year": null,
   "cat": "music"
  },
  {
   "n": 177,
   "title": "Explorers Collection #9 - FRB-2 [06-06-1984]",
   "file": "177 - Explorers Collection #9 - FRB-2 [06-06-1984].mp3",
   "art": "_art/177.jpg",
   "dur": 1875600,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 178,
   "title": "Explorers Collection #10 - DRM-1 [07-06-1984]",
   "file": "178 - Explorers Collection #10 - DRM-1 [07-06-1984].mp3",
   "art": "_art/178.jpg",
   "dur": 1748200,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 179,
   "title": "Explorers Collection #11 - PAMC-1 [27-06-1984]",
   "file": "179 - Explorers Collection #11 - PAMC-1 [27-06-1984].mp3",
   "art": "_art/179.jpg",
   "dur": 2785400,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 180,
   "title": "Explorers Collection #12 - DRM-3 [17-07-1985]",
   "file": "180 - Explorers Collection #12 - DRM-3 [17-07-1985].mp3",
   "art": "_art/180.jpg",
   "dur": 2708700,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 181,
   "title": "Explorers Collection #13 - PAMC-2 [01-08-1984]",
   "file": "181 - Explorers Collection #13 - PAMC-2 [01-08-1984].mp3",
   "art": "_art/181.jpg",
   "dur": 2593700,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 182,
   "title": "Explorers Collection #14 - PAMC-3 [13-09-1984]",
   "file": "182 - Explorers Collection #14 - PAMC-3 [13-09-1984].mp3",
   "art": "_art/182.jpg",
   "dur": 1810500,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 183,
   "title": "Transforming Life's Challenges",
   "file": "183 - Transforming Life's Challenges.mp3",
   "art": "_art/183.jpg",
   "dur": 2719800,
   "year": null,
   "cat": "music"
  },
  {
   "n": 184,
   "title": "Explorers Collection #15 - BDS-1 [06-10-1984]",
   "file": "184 - Explorers Collection #15 - BDS-1 [06-10-1984].mp3",
   "art": "_art/184.jpg",
   "dur": 2774300,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 185,
   "title": "Explorers Session with SMT - 01",
   "file": "185 - Explorers Session with SMT - 01.mp3",
   "art": "_art/185.jpg",
   "dur": 1711800,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 186,
   "title": "Explorers Collection #17 - SRF-1 [08-10-1984]",
   "file": "186 - Explorers Collection #17 - SRF-1 [08-10-1984].mp3",
   "art": "_art/186.jpg",
   "dur": 2486500,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 187,
   "title": "Purrfect Hemi-Sync",
   "file": "187 - Purrfect Hemi-Sync.mp3",
   "art": "_art/187.jpg",
   "dur": 3601100,
   "year": null,
   "cat": "music"
  },
  {
   "n": 188,
   "title": "Explorers Collection #18 - SMT-2 [09-10-1984]",
   "file": "188 - Explorers Collection #18 - SMT-2 [09-10-1984].mp3",
   "art": "_art/188.jpg",
   "dur": 2546200,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 189,
   "title": "Explorers Session with SRJ - 3",
   "file": "189 - Explorers Session with SRJ - 3.mp3",
   "art": "_art/189.jpg",
   "dur": 2550000,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 190,
   "title": "Explorers Collection #20 - JGW-3 [19-10-1984]",
   "file": "190 - Explorers Collection #20 - JGW-3 [19-10-1984].mp3",
   "art": "_art/190.jpg",
   "dur": 3722900,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 191,
   "title": "Ethan's Milagro",
   "file": "191 - Ethan's Milagro.mp3",
   "art": "_art/191.jpg",
   "dur": 2692200,
   "year": null,
   "cat": "music"
  },
  {
   "n": 192,
   "title": "Explorers Collection #21 - LLJ-1 [25-10-1984]",
   "file": "192 - Explorers Collection #21 - LLJ-1 [25-10-1984].mp3",
   "art": "_art/192.jpg",
   "dur": 2596800,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 193,
   "title": "Explorers Collection #22 - DRM-2 [07-11-1984]",
   "file": "193 - Explorers Collection #22 - DRM-2 [07-11-1984].mp3",
   "art": "_art/193.jpg",
   "dur": 2505500,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 194,
   "title": "Explorers Collection #23 - ROJ-RV1 [09-11-1984]",
   "file": "194 - Explorers Collection #23 - ROJ-RV1 [09-11-1984].mp3",
   "art": "_art/194.jpg",
   "dur": 1396700,
   "year": null,
   "cat": "sessions"
  },
  {
   "n": 196,
   "title": "Human Plus: Attention",
   "file": "Human Plus - Attention.flac",
   "art": "_art/073.jpg",
   "dur": 3602800,
   "year": null,
   "cat": "hplus",
   "flac": "Other Hemi-Sync (FLAC)/Human Plus/Human Plus - Attention.flac",
   "hifi": true
  },
  {
   "n": 197,
   "title": "Human Plus: Brain Repairs & Maintenance",
   "file": "Human Plus - Brain Repairs & Maintenance.flac",
   "art": "_art/073.jpg",
   "dur": 3610800,
   "year": null,
   "cat": "hplus",
   "flac": "Other Hemi-Sync (FLAC)/Human Plus/Human Plus - Brain Repairs & Maintenance.flac",
   "hifi": true
  },
  {
   "n": 198,
   "title": "Human Plus: Imprint",
   "file": "Human Plus - Imprint.flac",
   "art": "_art/073.jpg",
   "dur": 3638400,
   "year": null,
   "cat": "hplus",
   "flac": "Other Hemi-Sync (FLAC)/Human Plus/Human Plus - Imprint.flac",
   "hifi": true
  },
  {
   "n": 199,
   "title": "Between Worlds",
   "file": "Between Worlds.flac",
   "art": "_art/099.jpg",
   "dur": 3144000,
   "year": null,
   "cat": "music",
   "flac": "Other Hemi-Sync (FLAC)/Between Worlds/Between Worlds.flac",
   "hifi": true
  },
  {
   "n": 200,
   "title": "Journeys Out of the Body: Condition A",
   "file": "Journeys Out Of The Body - Condition A.flac",
   "art": "_art/cat_joob.svg",
   "dur": 3600000,
   "year": null,
   "cat": "joob",
   "flac": "Other Hemi-Sync (FLAC)/Journeys Out of the Body/Journeys Out Of The Body - Condition A.flac",
   "hifi": true
  },
  {
   "n": 201,
   "title": "Journeys Out of the Body: Condition B",
   "file": "Journeys Out Of The Body - Condition B.flac",
   "art": "_art/cat_joob.svg",
   "dur": 3600000,
   "year": null,
   "cat": "joob",
   "flac": "Other Hemi-Sync (FLAC)/Journeys Out of the Body/Journeys Out Of The Body - Condition B.flac",
   "hifi": true
  },
  {
   "n": 202,
   "title": "Journeys Out of the Body: Condition C",
   "file": "Journeys Out Of The Body - Condition C.flac",
   "art": "_art/cat_joob.svg",
   "dur": 3600000,
   "year": null,
   "cat": "joob",
   "flac": "Other Hemi-Sync (FLAC)/Journeys Out of the Body/Journeys Out Of The Body - Condition C.flac",
   "hifi": true
  },
  {
   "n": 203,
   "title": "Journeys Out of the Body: Condition D",
   "file": "Journeys Out Of The Body - Condition D.flac",
   "art": "_art/cat_joob.svg",
   "dur": 3600000,
   "year": null,
   "cat": "joob",
   "flac": "Other Hemi-Sync (FLAC)/Journeys Out of the Body/Journeys Out Of The Body - Condition D.flac",
   "hifi": true
  },
  {
   "n": 204,
   "title": "Journeys Out of the Body: Introduction By Bob Monroe",
   "file": "Journeys Out Of The Body - Introduction By Bob Monroe.flac",
   "art": "_art/cat_joob.svg",
   "dur": 1894900,
   "year": null,
   "cat": "joob",
   "flac": "Other Hemi-Sync (FLAC)/Journeys Out of the Body/Journeys Out Of The Body - Introduction By Bob Monroe.flac",
   "hifi": true
  },
  {
   "n": 205,
   "title": "Journeys Out of the Body: Reinforcement Exercise Of Relaxation",
   "file": "Journeys Out Of The Body - Reinforcement Exercise Of Relaxation.flac",
   "art": "_art/cat_joob.svg",
   "dur": 3600000,
   "year": null,
   "cat": "joob",
   "flac": "Other Hemi-Sync (FLAC)/Journeys Out of the Body/Journeys Out Of The Body - Reinforcement Exercise Of Relaxation.flac",
   "hifi": true
  },
  {
   "n": 206,
   "title": "Lucid Dreaming: Exercise 1",
   "file": "Lucid Dreaming Series DVD - Exercise 1.flac",
   "art": "_art/cat_lucid.svg",
   "dur": 5421600,
   "year": null,
   "cat": "lucid",
   "flac": "Other Hemi-Sync (FLAC)/Lucid Dreaming/Lucid Dreaming Series DVD - Exercise 1.flac",
   "hifi": true
  },
  {
   "n": 207,
   "title": "Lucid Dreaming: Exercise 2",
   "file": "Lucid Dreaming Series DVD - Exercise 2.flac",
   "art": "_art/cat_lucid.svg",
   "dur": 5422700,
   "year": null,
   "cat": "lucid",
   "flac": "Other Hemi-Sync (FLAC)/Lucid Dreaming/Lucid Dreaming Series DVD - Exercise 2.flac",
   "hifi": true
  },
  {
   "n": 208,
   "title": "Lucid Dreaming: Exercise 3",
   "file": "Lucid Dreaming Series DVD - Exercise 3.flac",
   "art": "_art/cat_lucid.svg",
   "dur": 5402100,
   "year": null,
   "cat": "lucid",
   "flac": "Other Hemi-Sync (FLAC)/Lucid Dreaming/Lucid Dreaming Series DVD - Exercise 3.flac",
   "hifi": true
  },
  {
   "n": 209,
   "title": "Lucid Dreaming: Exercise 4",
   "file": "Lucid Dreaming Series DVD - Exercise 4.flac",
   "art": "_art/cat_lucid.svg",
   "dur": 28800000,
   "year": null,
   "cat": "lucid",
   "flac": "Other Hemi-Sync (FLAC)/Lucid Dreaming/Lucid Dreaming Series DVD - Exercise 4.flac",
   "hifi": true
  },
  {
   "n": 210,
   "title": "Mind Food: Concentration",
   "file": "Concentration.flac",
   "art": "_art/cat_mindfood.svg",
   "dur": 3501373,
   "year": null,
   "cat": "mindfood",
   "flac": "Other Hemi-Sync (FLAC)/Mind Food/Concentration.flac",
   "hifi": true
  },
  {
   "n": 211,
   "title": "Mind Food: Retain Recall Release",
   "file": "Retain Recall Release.flac",
   "art": "_art/cat_mindfood.svg",
   "dur": 1901133,
   "year": null,
   "cat": "mindfood",
   "flac": "Other Hemi-Sync (FLAC)/Mind Food/Retain Recall Release.flac",
   "hifi": true
  },
  {
   "n": 212,
   "title": "Mind Food: Sound Sleeper (With Verbal Guidance)",
   "file": "Sound Sleeper (With Verbal Guidance).flac",
   "art": "_art/cat_mindfood.svg",
   "dur": 2399773,
   "year": null,
   "cat": "mindfood",
   "flac": "Other Hemi-Sync (FLAC)/Mind Food/Sound Sleeper (With Verbal Guidance).flac",
   "hifi": true
  },
  {
   "n": 213,
   "title": "Mind Food: Sound Sleeper (non verbal, delta sleep)",
   "file": "Sound Sleeper (non verbal, delta sleep).flac",
   "art": "_art/cat_mindfood.svg",
   "dur": 1823413,
   "year": null,
   "cat": "mindfood",
   "flac": "Other Hemi-Sync (FLAC)/Mind Food/Sound Sleeper (non verbal, delta sleep).flac",
   "hifi": true
  },
  {
   "n": 214,
   "title": "Mind Food: Transcendence Non-Verbal",
   "file": "Transcendence Non-Verbal.flac",
   "art": "_art/cat_mindfood.svg",
   "dur": 2156213,
   "year": null,
   "cat": "mindfood",
   "flac": "Other Hemi-Sync (FLAC)/Mind Food/Transcendence Non-Verbal.flac",
   "hifi": true
  },
  {
   "n": 215,
   "title": "Mind Food: Transcendence Verbal",
   "file": "Transcendence Verbal.flac",
   "art": "_art/cat_mindfood.svg",
   "dur": 2187960,
   "year": null,
   "cat": "mindfood",
   "flac": "Other Hemi-Sync (FLAC)/Mind Food/Transcendence Verbal.flac",
   "hifi": true
  },
  {
   "n": 216,
   "title": "Manifesting: An Interview with Joe Gallenberger",
   "file": "An Inteview with Joe Gallenberger.flac",
   "art": "_art/cat_manifesting.svg",
   "dur": 1355573,
   "year": null,
   "cat": "manifesting",
   "flac": "Other Hemi-Sync (FLAC)/MindFood - Manifesting/An Inteview with Joe Gallenberger.flac",
   "hifi": true
  },
  {
   "n": 217,
   "title": "Manifesting: Experiencing Manifestation",
   "file": "Experiencing Manifestation.flac",
   "art": "_art/cat_manifesting.svg",
   "dur": 1917973,
   "year": null,
   "cat": "manifesting",
   "flac": "Other Hemi-Sync (FLAC)/MindFood - Manifesting/Experiencing Manifestation.flac",
   "hifi": true
  },
  {
   "n": 218,
   "title": "Manifesting: Relaxation Into Manifestation",
   "file": "Relaxation Into Manifestation.flac",
   "art": "_art/cat_manifesting.svg",
   "dur": 2520013,
   "year": null,
   "cat": "manifesting",
   "flac": "Other Hemi-Sync (FLAC)/MindFood - Manifesting/Relaxation Into Manifestation.flac",
   "hifi": true
  }
 ]
};
